force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>An entry representing an engagement for a given user</description>
    <label>Engagement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether this engagement is selectable for the related user</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>The end date of the engagement for the related user. After this date the user will not be able to select the engagement. If blank then no end date will be assumed.</description>
    <label>End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The start date for the engagement. Before this date the engagement can not be selected by the user.</description>
    <label>Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user related to this engagement</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/Engagement_Entry__c.object-meta.xml
<CustomObject>
    <description>Each record represents a block of time spent on a given engagement for a given user.</description>
    <label>Engagement Entry</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Entry__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>The end time of this engagement entry</description>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>The engagement that this entry relates to.</description>
    <label>Engagement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Engagement__c.User__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Entries</relationshipLabel>
    <relationshipName>Engagement_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The start time of this engagement entry</description>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ContinuumControllerTest.cls
@IsTest
public with sharing class ContinuumControllerTest {

    @TestSetup
    static void makeData(){
        Id p = [select id from profile where name = 'Standard User'].id;
        User user = new User(alias = 'c.user', email='test.user@example.org',
                emailencodingkey='UTF-8', lastname='Test', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive = true,
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
        
        insert user;

        Id ps = [SELECT Id from PermissionSet WHERE Name = 'Continuum_User'].id;

        PermissionSetAssignment psa = new PermissionSetAssignment
        (PermissionSetId = ps, AssigneeId = user.Id);
        insert psa; 

        List<Engagement__c> engagements = new List<Engagement__c>();

        engagements.add(new Engagement__c(
            User__c = UserInfo.getUserId(),
            Name = 'Active With Start Date but not user',
            Active__c = true,
            Start__c = Date.today().addMonths(-1)
        ));

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Active With Start Date',
            Active__c = true,
            Start__c = Date.today()
        )); // Active

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Inactive With Start Date',
            Active__c = false,
            Start__c = Date.today()
        ));

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Active With Start and End Date',
            Active__c = true,
            Start__c = Date.today(),
            End__c = Date.today().addMonths(1)
        )); // Active

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Inactive With Start and End Date',
            Active__c = false,
            Start__c = Date.today(),
            End__c = Date.today().addMonths(1)
        ));

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Inactive With Past Start',
            Active__c = false,
            Start__c = Date.today().addMonths(-1)
        ));

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Inactive With Past Start and Future End',
            Active__c = false,
            Start__c = Date.today().addMonths(-1),
            End__c = Date.today().addMonths(1)
        ));

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Active With Past Start',
            Active__c = true,
            Start__c = Date.today().addMonths(-1)
        )); // Active

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Active With Past Start and Future End',
            Active__c = true,
            Start__c = Date.today().addMonths(-1),
            End__c = Date.today().addMonths(1)
        )); // Active

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Active With Future Start',
            Active__c = false,
            Start__c = Date.today().addMonths(+1)
        ));

        engagements.add(new Engagement__c(
            User__c = user.Id,
            Name = 'Active With Past End',
            Active__c = false,
            Start__c = Date.today(),
            End__c = Date.today().addMonths(-1)
        ));

        User admin = [SELECT Id FROM User WHERE id =: UserInfo.getUserId()];

        System.runAs(admin){
            insert engagements;
        }
    }

    @IsTest
    static void getEngagementsTest() {
        User u = [SELECT id FROM User WHERE email = 'test.user@example.org'];
        System.runAs(u){
            List<ContinuumController.EngagementDto> response = ContinuumController.getAvailableEngagements();
            System.assertEquals(4, response.size());
            System.assertEquals('Active With Past Start', response[0].name); // Returns in alphabetical order
        }
    }

    @IsTest
    static void startEngagementEntryTest() {
        User u = [SELECT id FROM User WHERE email = 'test.user@example.org'];
        System.runAs(u){
            List<Engagement__c> engagements = [SELECT Id, Name, Start__c FROM Engagement__c WHERE Active__c  = true AND User__c = :UserInfo.getUserId() AND Start__c <= TODAY AND (End__c = NULL OR End__c >= TODAY)];
            System.assertEquals(4, engagements.size());

            // Start work on engagement 1
            ContinuumController.startEngagementEntry(engagements[0].Id);
            List<Engagement_Entry__c> entries = [SELECT Id, Name, Start__c, End__c, Engagement__c FROM Engagement_Entry__c WHERE End__c = NULL];
            System.assertEquals(1, entries.size());
            System.assertEquals(Datetime.now(), entries[0].Start__c);
            System.assertEquals(NULL, entries[0].End__c);
            System.assertEquals(engagements[0].Id, entries[0].Engagement__c);

            // Start work on engagement 2
            ContinuumController.startEngagementEntry(engagements[1].Id);
            entries = [SELECT Id, Name, Start__c, End__c, Engagement__c FROM Engagement_Entry__c WHERE End__c = NULL]; // Check new engagement entry
            System.assertEquals(1, entries.size());
            System.assertEquals(Datetime.now(), entries[0].Start__c);
            System.assertEquals(NULL, entries[0].End__c);
            System.assertEquals(engagements[1].Id, entries[0].Engagement__c);

            entries = [SELECT Id, Name, Start__c, End__c, Engagement__c FROM Engagement_Entry__c WHERE End__c != NULL]; // Check closed engagement entry
            System.assertEquals(1, entries.size());
            System.assertEquals(Datetime.now(), entries[0].Start__c);
            System.assertEquals(Datetime.now(), entries[0].End__c);
            System.assertEquals(engagements[0].Id, entries[0].Engagement__c);


            // Select engagement 2 again
            ContinuumController.startEngagementEntry(engagements[1].Id);
            entries = [SELECT Id, Name, Start__c, End__c, Engagement__c FROM Engagement_Entry__c WHERE End__c = NULL]; // Check new engagement entry
            System.assertEquals(1, entries.size());
            System.assertEquals(Datetime.now(), entries[0].Start__c);
            System.assertEquals(NULL, entries[0].End__c);
            System.assertEquals(engagements[1].Id, entries[0].Engagement__c);

            entries = [SELECT Id, Name, Start__c, End__c, Engagement__c FROM Engagement_Entry__c WHERE End__c != NULL]; // Check closed engagement entry
            System.assertEquals(1, entries.size(), 'If the active engagement is selected again, it should not replace with a new entry.');
        }
    }

    @IsTest
    static void endEngagementsTest() {
        User u = [SELECT id FROM User WHERE email = 'test.user@example.org'];
        System.runAs(u){
            List<Engagement__c> engagements = [SELECT Id, Name, Start__c FROM Engagement__c WHERE Active__c  = true AND User__c = :UserInfo.getUserId() AND Start__c <= TODAY AND (End__c = NULL OR End__c >= TODAY)];
            System.assertEquals(4, engagements.size());

            List<Engagement_Entry__c> newEntries = new List<Engagement_Entry__c>();
            // Start work on engagements (multiple would never be active at the same time in real life)
            newEntries.add(new Engagement_Entry__c(Engagement__c = engagements[0].Id, Start__c = Datetime.now()));
            newEntries.add(new Engagement_Entry__c(Engagement__c = engagements[1].Id, Start__c = Datetime.now()));
            newEntries.add(new Engagement_Entry__c(Engagement__c = engagements[2].Id, Start__c = Datetime.now()));
            insert newEntries;

            // End engagements
            ContinuumController.endEngagements();
            List<Engagement_Entry__c> entries = [SELECT Id, Name, Start__c, End__c, Engagement__c FROM Engagement_Entry__c WHERE End__c != NULL]; // Check closed engagement entries
            System.assertEquals(3, entries.size());
            for (Engagement_Entry__c e : entries) {
                System.assertEquals(Datetime.now(), e.Start__c);
                System.assertEquals(Datetime.now(), e.End__c);
                System.assertNotEquals(NULL, e.Engagement__c);
            }
        }
    }
}