force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>An entry representing an engagement for a given user</description>
    <label>Engagement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>The end date of the engagement for the related user. After this date the user will not be able to select the engagement. If blank then no end date will be assumed.</description>
    <label>End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The start date for the engagement. Before this date the engagement can not be selected by the user.</description>
    <label>Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user related to this engagement</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/Engagement_Entry__c.object-meta.xml
<CustomObject>
    <description>Each record represents a block of time spent on a given engagement for a given user.</description>
    <label>Engagement Entry</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Entry__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>The end time of this engagement entry</description>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>The engagement that this entry relates to.</description>
    <label>Engagement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Engagement__c.User__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Entries</relationshipLabel>
    <relationshipName>Engagement_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The start time of this engagement entry</description>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ContinuumController.cls
@RestResource(urlMapping='/EngagementEntries/*')
global with sharing class ContinuumController {
    @AuraEnabled
    public static List<EngagementDto> getAvailableEngagements() {
        List<Engagement__c> engagements = EngagementSelector.getAvailableEngagements();
        List<EngagementDto> response = new List<EngagementDto>();
        if (engagements.size() > 0) {
            for (Engagement__c e : engagements) {
                System.debug(e);
                System.debug(e.Engagement_Entries__r.size());

                response.add(new EngagementDto(e.Id, e.Name, (e.Engagement_Entries__r.size() > 0)));
            }
        }
        System.debug(response);
        return response;
    }

    public with sharing class EngagementDto {
        @AuraEnabled
        public Id id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public boolean selected;
        public EngagementDto(Id id, String name, Boolean selected) {
            this.id = id;
            this.name = name;
            this.selected = selected;
        }
    }

    @AuraEnabled
    @HttpPost
    global static void startEngagementEntry(String engagementId) {
        if (endEngagementsExceptId(engagementId) == false) return;
        // Save new engagement with current start time for the given ID
        Engagement_Entry__c entry = new Engagement_Entry__c(Engagement__c = engagementId, Start__c = Datetime.now());
        insert entry;
    }

    @AuraEnabled
    public static void endEngagements() {
        endEngagementsExceptId(null);
    }

    private static boolean endEngagementsExceptId(String newEngagement) {
        // End and close all open engagements
        List<Engagement_Entry__c> openEntries = [SELECT Id, Engagement__c FROM Engagement_Entry__c WHERE Engagement__r.User__c = :UserInfo.getUserId() AND End__c = NULL];
        if (openEntries.size() > 0) {
            for(Engagement_Entry__c e : openEntries) {
                if (newEngagement != '' && e.Engagement__c == Id.valueOf(newEngagement)) return false; // Don't end the engagement if it is the current active one.
                e.End__c = Datetime.now();
            }
        }
        update openEntries;
        if (newEngagement == '') return false; // No new engagement
        return true;
    }
}