force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>An entry representing an engagement for a given user</description>
    <label>Engagement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether this engagement is selectable for the related user</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>The end date of the engagement for the related user. After this date the user will not be able to select the engagement. If blank then no end date will be assumed.</description>
    <label>End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The start date for the engagement. Before this date the engagement can not be selected by the user.</description>
    <label>Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user related to this engagement</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/Engagement_Entry__c.object-meta.xml
<CustomObject>
    <description>Each record represents a block of time spent on a given engagement for a given user.</description>
    <label>Engagement Entry</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Entry__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>The end time of this engagement entry</description>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>The engagement that this entry relates to.</description>
    <label>Engagement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Engagement__c.User__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Entries</relationshipLabel>
    <relationshipName>Engagement_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Engagement_Entry__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The start time of this engagement entry</description>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EngagementSelector.cls
public with sharing class EngagementSelector {
    public static List<Engagement__c> getAvailableEngagements() {
        // return all active engagements for the current user in the given timeframe
        return [SELECT Id, Name, (SELECT ID FROM Engagement_Entries__r WHERE End__c = NULL) FROM Engagement__c 
                                            WHERE Active__c  = true 
                                            AND User__c = :UserInfo.getUserId()
                                            AND Start__c <= TODAY 
                                            AND (End__c = NULL OR End__c >= TODAY) 
                                            ORDER BY Name ASC];
    }
}